server:
  port: 8080
  tomcat:
    use-relative-redirects: true

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy  #
    url: jdbc:log4jdbc:mysql://localhost:3306/CrowdBuying?serverTimezone=Asia/Seoul
    username: cb
    password: cb

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://y4j-rds-instance.cteyrdjospoe.ap-northeast-2.rds.amazonaws.com:3306/y4j_rds?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: crowd_buying
#    password: zm_qk135